FROM your-org-clients:latest AS builder

RUN npm run build

FROM caddy:2.9.1

COPY --from=builder /app/clients/spas/dist /srv/spas
COPY ./deploy/prod/remote-assets/config /etc/caddy/
COPY ./deploy/prod/remote-assets/health-assets /srv/health-assets
