auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 5m

limits_config:
  retention_period: 168h # 7 days
  # Optional: Set max storage per tenant
  max_global_streams_per_user: 10000
  max_line_size: 256000

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
